### ISSUE TITLE
Version number not updated in 0.1.1

### ISSUE THREAD

**Issue by Sobuno** [LinuxChristian/pyW215#1]
The version number in setup.py should be updated to version 0.1.1.

I was wondering why my Home Assistant was taking so long to boot and looked at the logs as it booted - on every boot, it was trying to install a new version of pyW215 since the current version was not meeting the requirements because it thinks it installed 0.1.

**Comment by LinuxChristian** [comment]
Thanks for the bugfix. Let me know if everything works now then I will close the issue.

**Comment by Sobuno** [comment]
Just did a couple of restarts. First one downloaded pyW215 again and the second one passed right through, so it seems to work perfectly now :)
