### ISSUE TITLE
import request fails

### ISSUE THREAD

**Issue by thecalle** [LinuxChristian/pyW215#11]
To make code run with Python 2.7, code must be changed from:
from **urllib.request** import Request, urlopen
from **urllib.error** import URLError, HTTPError
to
from **urllib2** import Request, urlopen
from **urllib2** import URLError, HTTPError

**Comment by LinuxChristian** [comment]
The code is written for python 3.x. Compatibility with both 2.x and 3.x can be tricky but I will look into fixing the import of urllib.

**Comment by clach04** [comment]
I have something that works for me, @thecalle do you have time to test PR #15?

**Comment by LinuxChristian** [comment]
@clach04 should have fixed it now. However I use python3 so I cannot guarantee that a future change may not break compatibility. Let me know if this becomes a issue again.

**Comment by thecalle** [comment]
Good news.

I will test it as soon as possibile.

Francesco
