### ISSUE TITLE
Publish on pypi 

### ISSUE THREAD

**Issue by andrey-git** [LinuxChristian/pyW215#12]
Christian, could you publish this package on Pypi, so it can be fetched without specifying the github URL?

https://github.com/home-assistant/home-assistant/issues/7069

**Comment by LinuxChristian** [comment]
Sorry about the late response. My internet has been spotty for a while. I look into it ASAP.

**Comment by LinuxChristian** [comment]
Sorry about the extremely slow progress on this. My whole HASS setup is currently down since I am renovating my house from top to bottom.
But I have finally managed to make a pypi package: https://pypi.org/project/pyW215/

Let me know if I need to do anything else.

**Comment by andrey-git** [comment]
Thanks!
