### ISSUE TITLE
D-Link W110 smart switch (only state changing is supported)

### ISSUE THREAD

**Issue by clach04** [LinuxChristian/pyW215#16]
readme states:

> D-Link W110 smart switch (only state changing is supported)

With my device, state reporting works:

    print(sp.state)

works for my DSP-W110 RevB1 device with v2.03 firmware.

I'm not sure what limits this might be referring to (this device doesn't do anything else)

**Comment by LinuxChristian** [comment]
The later devices (W215) also report temperature and different power consumption stats. The versions of W110 I have seen do not support these metrics.

**Comment by clach04** [comment]
I think I understand, how about changing to:

> D-Link W110 smart switch (only state viewing and changing is supported)

I.e. document "viewing".

**Comment by LinuxChristian** [comment]
Fixed in commit 5b5b6a89a0842f1534b39d39ab88b4d93de0e217
