### ISSUE TITLE
Error when performing soap calls

### ISSUE THREAD

**Issue by Finnsk3** [LinuxChristian/pyW215#19]
Hi,

I have 3 W215's with 1.24 firmware, I am unsure what the deal is with 2.x firmware as the dlink site shows 1.24 as being the latest firmware.

I can't get a response back from pyW215, dsp-w215-hnap or homeassistant on any of my switches. I have also written my own w215 library in PHP but get the same response from the soap calls.

pyW215 gets a successful login but any further soap queries returns errors:
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetCurrentPowerConsumptionResponse xmlns="http://purenetworks.com/HNAP1/"><GetCurrentPowerConsumptionResult>ERROR</GetCurrentPowerConsumptionResult><CurrentConsumption>0</CurrentConsumption></GetCurrentPowerConsumptionResponse></soap:Body></soap:Envelope>`

my_cgi returns:
Firmware External Version: V1.24
Firmware Internal Version: V1.24B01
Date: 01, Mar, 2016
CheckSum: 0x073C5536
WLAN Domain: AU
Firmware Query: http://wrpd.dlink.com.tw/router/firmware/query.asp?model=DSP-W215_Ax_Default
Kernel: 2.6.31, B0067, Date=Thu, 21, May, 2015
Apps: 0604, Date=Wed, 23, Dec, 2015
WLAN Driver: ap121-9.2.0.915, B0008, Fri, 03, Aug, 2012
LAN MAC: 54:B8:0A:7C:6C:FF
WLAN MAC: 54:B8:0A:7C:6C:FF
SSID: DSP-6CFF
Factory Default= 0
DCH_ID: 4db5a8dc49df2c3775e693147aaef71b
DCH_Agent: Failure

**Comment by Finnsk3** [comment]
Hitting /common/info.cgi I get this, showing the 2.16 firmware. :|
Atleast now I can log my wattage, I wish there was a way to turn the power on and off via this :(

Firmware Date: Tue, 1 Mar 2016
KERNEL: 2.6.31, Build: 0067, Date: Thu, 21, May, 2015
Application: 2.0, Build: 0604, Date: Wed, 23, Dec, 2015
WLAN Version: ap121-9.2.0.915, Build: 0008, Date: Fri, 03, Aug, 2012
Wireless Domain: 0x23
SSID: DSP-6A21
LAN MAC: 54:B8:0A:7C:6A:21
WLAN MAC 0: 54:B8:0A:7C:6A:21
WLAN MAC 1: 26:B8:0A:7C:6A:21
WLAN 0 Channel List: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
WLAN 1 Channel List: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
Default: 0
checksum: 0x073C5536
HW Ver: A1
BL-Version: ver1.00b04
BL-Checksum: 0x0074CEBD
Language: DISABLE
CONFIG_VERSION: 2.06
Meter Firmware Version: ver2.16
Meter Watt: 1720.4

**Comment by Finnsk3** [comment]
Update, I got it working.

I had to use the legacy mode.
Interestingly, sp = SmartPlug('192.168.1.175', 'pwd', True) didn't work, I had to change the actual class initialisation to get it to actually use legacy mode. No idea why, I have never written python before but even if I passed True when creating an instance of the object use_legacy_protocol was always False.

**Comment by LinuxChristian** [comment]
@Finnsk3, Great you got it working! Thanks for the info.. I will look into if we have a bug with the legacy mode.
