### ISSUE TITLE
Is there an tutorial for an noobie?

### ISSUE THREAD

**Issue by Platypuschan** [LinuxChristian/pyW215#24]
I´m very inexperienced in python, is there a quick tutorial how to set up this script?

**Comment by LinuxChristian** [comment]
Hi @Schnabelriechen,

If you are new to python I would suggest this guide: https://www.python.org/about/gettingstarted/

If you just want to get started with the library I hope the code example from the README can help you

```
#!python3
from pyW215.pyW215 import SmartPlug, ON, OFF

sp = SmartPlug('192.168.1.110', '******')
# Where ****** is the "code pin" printed on the setup card

# Get values if available otherwise return N/A
print(sp.current_consumption)
print(sp.temperature)
print(sp.total_consumption)

# Turn switch on and off
sp.state = ON
sp.state = OFF
```

**Comment by Platypuschan** [comment]
Thank you very much for your quick reply 👍 
First off: i´m really new to python... But it took me some time to figure out how this works... 
Saving the first four  rows and the sp.state = ON/OFF into an *.py file, chmod +x it, and open it with python3 <yourscript>. Somehow it didn´t work with my normal python. Maybe you could mention those steps in the readme for noobies like me...

**Comment by LinuxChristian** [comment]
Thanks for the suggestion. I will update the readme the next time I make changes.
