### ISSUE TITLE
Please make a 6.0.0 tar.gz release for redistribution.

### ISSUE THREAD

**Issue by onkelbeh** [LinuxChristian/pyW215#31]
Hi Christian,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).

Therefor I would need a release file in tar.gz format.
Home Assistant currently requires: `pyW215==0.6.0`

A release on Github would be OK, currently there is none for `0.6.0`, so today I added a [fork to my Overlay](https://github.com/onkelbeh/HomeAssistantRepository/commit/66df02c4b2c14ccaea344834d875e8911346f79e). Took me 2 clicks, so it would you.
Generally, a tar.gz release on Pypi **would be preferred**, because this could take use of Gentoo's mirror system.

Most of the other integrations do both.
Thanks
 \B.

**Comment by LinuxChristian** [comment]
Hi @onkelbeh,

I am sorry for the late reply. Did you manage to find the releases at https://github.com/LinuxChristian/pyW215/releases?

**Comment by onkelbeh** [comment]
Sorry for my late reply, lost track of this.
Just went through old tickets to clean up.

The only referenced version from HA is pyW215-0.7.0, everything is OK now.
If you are interested, the current Ebuild is [here](https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/pyW215).
