### ISSUE TITLE
how do i install this on hassio

### ISSUE THREAD

**Issue by rachnov55** [LinuxChristian/pyW215#32]
hi, sorry if i shouldn't be posting about this.

i only recently installed hassio (home assistant) on my raspberry pi...i have no idea how to install this.  

I used raspbian before and am aware of how to git pull there, but I have no idea how to do it now since i can't open a terminal

**Comment by LinuxChristian** [comment]
Hi @rachnov55 . Sorry for the late reply. Github didn't notify me of your question :unamused: 

In hass you need to edit your `configuration.yaml` file and add this as a new `switch`. I think they have a in-browser edit option now. There is a small example with the code you need to add in the docs https://www.home-assistant.io/integrations/dlink/.

Hope it helps.
