### ISSUE TITLE
Support for DSP-W118?

### ISSUE THREAD

**Issue by Vinz87** [LinuxChristian/pyW215#35]
Hi, would it be possible to add support for DSP-W118 smart plug?

**Comment by LinuxChristian** [comment]
Hi @Vinz87, unfortunately, I don't have access to a DSP-W118 so I cannot reverse the protocol. I am happy to accept any changes that would add support but I will not have time to do the work myself.

However, as I understand the latest changes to the plug they have completly changed their communication protocol. So I think it would require a major rewrite to support it.

**Comment by tymzang** [comment]
@Vinz87: as I see now many people demand HA integration with DSP-W118 since their app is so stupid...

**Comment by Vinz87** [comment]
Originally I wanted to be able to toggle the "privacy mode" from HA, but without an integration it's not possible, so I ended up using a smart plug which I toggle from HA to switch on and off the  cameras when they're not needed.
Having a full integration in HA would obviously be cleaner.

**Comment by tymzang** [comment]
@Vinz87 : I have a solution for DSP-W118, but it is not a good way... You can link DSP-W118 to Google Assistant... Then Google Assistant can be linked to Hassio... The delay is not so much, 1-2 second... but you need Cloud, it is not Local anymore

**Comment by Vinz87** [comment]
> Originally I wanted to be able to toggle the "privacy mode" from HA, but without an integration it's not possible, so I ended up using a smart plug which I toggle from HA to switch on and off the cameras when they're not needed.
> Having a full integration in HA would obviously be cleaner.

sorry I was confusing here. I was thinking about D-Link cameras which I connected to the smart plugs DSP-W118, not viceversa :)

**Comment by Vinz87** [comment]
> @Vinz87 : I have a solution for DSP-W118, but it is not a good way... You can link DSP-W118 to Google Assistant... Then Google Assistant can be linked to Hassio... The delay is not so much, 1-2 second... but you need Cloud, it is not Local anymore

The only solution I found passes through IFTTT, which is working correctly but IFTTT has recently introduced a free plan with strong limitations on the number of integrations you can use.
So I already use a solution which is not local and does have some delay.

I will look into your suggestion, my goal would be to not rely on IFTTT anymore. So I have to look into the Google Assistant integration into HA, and how to link the smart plug to Google Assistant, correct?

**Comment by tymzang** [comment]
@Vinz87 : Don't use IFTTT, even they give your premium, it still have a lot delay... I tried and delete IFTTT account.

You only need to integrate GA to HA... every devices in GA will be synced to HA... If you have "Device ABC" on both HA and GA, after syncing, you will have 2 "Device ABC" on HA

**Comment by tymzang** [comment]
@Vinz87 : this is just temporary solution... I wish DSP-W118 will be official integrated to HA for Local purpose

**Comment by Vinz87** [comment]
@tymzang I added the smart plug to Google Assistant, I tried [this](https://www.home-assistant.io/integrations/google_assistant/) tutorial (manual setup) for linking Google Assistant with Home Assistant. However it seems to me that the link is only in the HA -> Google direction, while my objective is to have the Google's plug control replicated in HA.
Is that the right tutorial to follow?

**Comment by LinuxChristian** [comment]
Sounds like you found a workaround. I am still happy to accept a PR to add support but it sounds like the workaround is less work :slightly_smiling_face:

**Comment by Vinz87** [comment]
> Sounds like you found a workaround. I am still happy to accept a PR to add support but it sounds like the workaround is less work 🙂

My current usage is through IFTTT D-Link integration, which has an easy to use trigger for them.
If you assume the user provides an IFTTT API key, it's easy to integrate since it only takes a HTTP requests to trigger something to IFTTT, and link the trigger to the ON/OFF command of the smart plugs.
