### ISSUE TITLE
Support for W110 smartplug broke in release 0.3.x

### ISSUE THREAD

**Issue by LinuxChristian** [LinuxChristian/pyW215#6]
With the following error message

```
Traceback (most recent call last):
File "W110-test.py", line 4, in
cc = sp.current_consumption
File "/home/pi/.homeassistant/deps/pyW215/pyW215.py", line 155, in current_consumption
res = self.SOAPAction('GetCurrentPowerConsumption', 'CurrentConsumption', self.moduleParameters("2"))
File "/home/pi/.homeassistant/deps/pyW215/pyW215.py", line 143, in SOAPAction
value = root.find('.//{http://purenetworks.com/HNAP1/}%s' % (responseElement)).text
AttributeError: 'NoneType' object has no attribute 'text'
```

Also see: https://github.com/home-assistant/home-assistant/issues/3386

**Comment by LinuxChristian** [comment]
@Shadex12 I need you to go into the HA .deps folder and find the file pyW215/pyW215.py. Open the file and find line 143,

`value = root.find('.//{http://purenetworks.com/HNAP1/}%s' % (responseElement)).text`

Just above it write,

```
print(response)
print(xmlData)
```

Then run your small test script again and see what you get.

**Comment by Shadex12** [comment]
@LinuxChristian I modified the file so it looks like this:

```
    print(response)
    print(xmlData)
    value = root.find('.//{http://purenetworks.com/HNAP1/}%s' % (responseElement)).text
    if value is None and self._error_report is False:
        _LOGGER.warning("Could not find %s in response." % responseElement)
        self._error_report = True
        return None

    self._error_report = False
    return value
```

This is what i get when I run the test file. 

<http.client.HTTPResponse object at 0x76a16450>
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">soap:Body<GetCurrentPowerConsumptionResponse xmlns="http://purenetworks.com/HNAP1/"><GetCurrentPowerConsumptionResult>ERROR_NOT_SUPPORTED</GetCurrentPowerConsumptionResult></GetCurrentPowerConsumptionResponse>/soap:Body/soap:Envelope
Traceback (most recent call last):
  File "W110-test.py", line 4, in <module>
    cc = sp.current_consumption
  File "/home/pi/.homeassistant/deps/pyW215/pyW215.py", line 157, in current_consumption
    res = self.SOAPAction('GetCurrentPowerConsumption', 'CurrentConsumption', self.moduleParameters("2"))
  File "/home/pi/.homeassistant/deps/pyW215/pyW215.py", line 145, in SOAPAction
    value = root.find('.//{http://purenetworks.com/HNAP1/}%s' % (responseElement)).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by LinuxChristian** [comment]
Do you know if your plug supports showing power consumption?

**Comment by Shadex12** [comment]
It does not. Or temperature. This why is suspect these issues are occurring.

**Comment by LinuxChristian** [comment]
I see... then the problem is related to state attributes which have been added to the new release of the HA component but expects devices to always return consumption and temperature.. I will see if I can fix it directly in the library. Could you try the following code to verify that your switch still is able to turn on and off,

```
from pyW215 import SmartPlug

sp = SmartPlug('192.168.1.110', '******')
# cc = sp.current_consumption
sp.state = "OFF"
sp.state = "ON"
```

**Note**: This should turn your plug off and then on. Just if you have anything important plugged in.

**Comment by Shadex12** [comment]
Yes. That worked well. Turned off then back on. Here is the output:

`<http.client.HTTPResponse object at 0x765d9230>
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><SetSocketSettingsResponse xmlns="http://purenetworks.com/HNAP1/"><SetSocketSettingsResult>OK</SetSocketSettingsResult></SetSocketSettingsResponse></soap:Body></soap:Envelope>
<http.client.HTTPResponse object at 0x765d96f0>
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><SetSocketSettingsResponse xmlns="http://purenetworks.com/HNAP1/"><SetSocketSettingsResult>OK</SetSocketSettingsResult></SetSocketSettingsResponse></soap:Body></soap:Envelope>
`

**Comment by LinuxChristian** [comment]
Great! I just need too see how best to fix it and submit a patch to the HA guys. Might take a day or two. So the fix should be available in next HA release (either hotfix 0.28.3-4 or 0.29). While you wait find the location where you installed HA. You can find it by running,

`find /usr/local | grep dlink.py; find /home/ | grep dlink.py`

It should return some like,

/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/dlink.py

Edit the file and remove the function below, 

```
    @property
    def device_state_attributes(self):
        """Return the state attributes of the device."""
        ui_temp = self.units.temperature(int(self.smartplug.temperature),
                                         TEMP_CELSIUS)
        temperature = "{} {}".format(ui_temp, self.units.temperature_unit)
        current_consumption = "{} W".format(self.smartplug.current_consumption)
        total_consumption = "{} W".format(self.smartplug.total_consumption)

        attrs = {
            ATTR_CURRENT_CONSUMPTION: current_consumption,
            ATTR_TOTAL_CONSUMPTION: total_consumption,
            ATTR_TEMPERATURE: temperature
        }

        return attrs
```

After a restart your HA should be back to normal.

**Comment by Shadex12** [comment]
They now show up as "unnamed devices" but I was able to add them back into the configuration and they are working. 

Thanks for all your help! If you need someone to test in the future, please don't hesitate to contact me.

**Comment by LinuxChristian** [comment]
I have a new version ready. Could I get you to add the following to your dlink.py file in HA

```
    @property
    def device_state_attributes(self):
        """Return the state attributes of the device."""
        try:
            ui_temp = self.units.temperature(int(self.smartplug.temperature),
                                             TEMP_CELSIUS)
        except:
            ui_temp = 'N/A'

        temperature = "{} {}".format(ui_temp, self.units.temperature_unit)
        current_consumption = "{} W".format(self.smartplug.current_consumption)
        total_consumption = "{} W".format(self.smartplug.total_consumption)

        attrs = {
            ATTR_CURRENT_CONSUMPTION: current_consumption,
            ATTR_TOTAL_CONSUMPTION: total_consumption,
            ATTR_TEMPERATURE: temperature
        }

        return attrs
```

Then overwrite your pyW215.py file from deps with the latest from [github](https://raw.githubusercontent.com/LinuxChristian/pyW215/master/pyW215/pyW215.py),

Now hopefully you should not get errors in HA. If you click the switch in the HA web interface you should see N/A next to all the attributes.

If this works I will submit the patch to HA and wait for the next release.

**Comment by Shadex12** [comment]
@LinuxChristian This is working perfectly. 

Thanks again.
