### ISSUE TITLE
Auth fails with 500: Internal Server Error after some time

### ISSUE THREAD

**Issue by fpytloun** [LinuxChristian/pyW215#9]
Hello,

I am using DSP-W215 with firmware 2.22 and controlling it using Homeassistant and this plugin: https://home-assistant.io/components/switch.dlink/

I have found out that after some time of flawless work (eg. couple of days), it will stop working returning `HTTP Error 500: Internal Server Error` in `auth` method from URL `http://192.168.33.171/HNAP1/`.

Even login form in D-Link's web interface does not work so it's obviously some bug in that firmware and not in pyW215 but I am curious if anyone seen this issue and possibly figure out how to solve it?
Next step will be to contact d-link support so we'll see.

**Comment by LinuxChristian** [comment]
I have had the same problems with both my switches. It varies a lot how long they remain up. Some times it's a couple of days but now one switch has been running for weeks without problems.
I would also expect a firmware problem but it could also be that some API calls creates a bug. Have anyone had the same problems using only the app?

So far I have only worked around the problem by fixing the library and Home assistant so it returns N/A on the 500 error. It would however be great not having to unplug the switches once in a while :smile:

**Comment by IvayloIliev** [comment]
I am experiencing the same problem Using openhab and the exec binding (calling python customTool.py where each time a new object/connection is created for each status update and state change). I will try to investigate whether it is due to the many connections mixing up.

**Comment by mikepm35** [comment]
I was experiencing this same issue with two W110's and Home Assistant.  In doing some debugging, auth requests started to fail after 7-9 hours, independent of whether 1 or 2 switches were active.  What was interesting was that the failures were never 100%, but the frequency of the auth denials increased over time.  Restarting the Home Assistant service did not help, but if I put retry logic in for the auth request it would eventually succeed.  I could not login to the switch directly, but the D-Link app continued to work.

I patched the issue in my branch by detecting the model on initialization, and then skipping the unsupported actions ("GetCurrentPowerConsumption", "GetPMWarningThreshold", "GetCurrentTemperature").  I haven't had any auth request failures since using this (~5 days ago).

**Comment by LinuxChristian** [comment]
Sorry for the late reply. Interesting. Perhaps it can only handle a certain number of requests to non-existing functions.

Do you use it with Home assistant (HA)? If so what does HA report for the actions you skip? N/A?

**Comment by IvayloIliev** [comment]
Hi again. Yes I am using it with OpenHAB and reports "Failed to authenticate with SmartPlug 192.168.x.x" + N/A at the end. I also tested with multiple instances of the pyW215 script so it not related to some threading issue on the socket. I just got some time to change my script to use Flask (so I can have static global object for all my requests to the socket) and will report back after a few days of testing.

I can also post the Flask code here if you are interested, even though it is not much of a code more like a wrapper.

Also a good idea would be just to test with a loop creating new objects is there really a limit. This will be my next move if I have problems with the Flask code.

**Comment by LinuxChristian** [comment]
Anything new on this issue?

**Comment by LinuxChristian** [comment]
I just merged a fix for the v1.25 firmware update where they introduced an auth limit to stop brute-force attaches. That maybe what is also happing here.. The newest version of the library (v0.6.0) supports this for legacy devices (v1.24 and v1.25).

I will try activate this for all firmware versions locally and see how my plugs behave. If anyone wants to try on their own plug just switch to the legacy support mode and see if the plugs still become inactive after a while.

**Comment by frog32** [comment]
It has been two months since the last update. Does that mean that you did not have any issues since? If yes would it be possible to ship a release with that fix?

**Comment by ghost** [comment]
I'm on the V1.25 also, seems there's a 3 try limit? After 3 queries I get the error below.

Reboot of switch fixes it. I'm not sure how long the timeout value is, but it doesn't' seem to reset. 

```
Traceback (most recent call last):
  File "/home/pi/Documents/Aquarium/Lights/TurnKilliLightOn.py", line 10, in <module>
    sp = SmartPlug('192.168.0.60', '105348')
  File "/home/pi/Documents/Aquarium/Lights/pyw215.py", line 60, in __init__
    self.model_name = self.SOAPAction(Action="GetDeviceSettings", responseElement="ModelName", params = "")
  File "/home/pi/Documents/Aquarium/Lights/pyw215.py", line 131, in SOAPAction
    self.authenticated = self.auth()
  File "/home/pi/Documents/Aquarium/Lights/pyw215.py", line 318, in auth
    Challenge = root.find('.//{http://purenetworks.com/HNAP1/}Challenge').text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by LinuxChristian** [comment]
@frog32 Have you tried the v0.6.0 release? That is integrated into the latest version of home assistant since Sepember 1th.
@willd-easy Are you using the v0.6.0 release with your v1.25 plug?

Right now I still have a hard time finding a pattern in this bug.
 * @willd-easy fails after 3 trys
 * @mikepm35 fails after 7-9 hours but is dependent on the number of active plugs
 * I have not found a pattern in my own failures

I have not had time to test the latest update (v0.6.0) but hope to find time soon.

If anyone has time to do a bit more test please post your findings. I think what we need now is more information to pin where the bug could be.

**Comment by LinuxChristian** [comment]
I think I have made progress. The following scripts has been running for over a week without a single failure.

```python
#!python3
from pyW215.pyW215 import SmartPlug, ON, OFF
from time import sleep
from datetime import datetime

sp = SmartPlug('192.168.x.x', '**********')

while True:
    print(sp.current_consumption)
    print(sp.temperature)
    print(sp.total_consumption)

    # Turn switch on and off
    if sp.state == OFF:
        sp.state = ON
    elif sp.state == ON:
        sp.state = OFF
    else:
        print("Device failed at")
        print(datetime.now())
        exit()

    sleep(60)
```
My current guess is that home assistant is querying the device too often. I will try to wrap the device through MQTT and see it that helps.

**Comment by frog32** [comment]
We could also reduce the polling interval in home assistant. I can confirm that after some time this still happens but for me it locks up after more than a week.

**Comment by LinuxChristian** [comment]
@frog32 I have been looking for that feature. Knows that it exists but my google skills were not powerful enough. Do you know where it is?

**Comment by frog32** [comment]
I think this could be achieved by using throttle on the update method here:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/dlink.py#L140

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/util/__init__.py#L236

**Comment by LinuxChristian** [comment]
Think that might solve some of the problem. I will look into it.

**Comment by henrikhjelm** [comment]
have the same problem, any news on it ?

**Comment by LinuxChristian** [comment]
Sorry about the late reply. Things have been swamped so I have not had the time yet. I will look into it now and start testing.

**Comment by LinuxChristian** [comment]
Quick update. My switch is still going strong. I will give it a week more and if it still works commit the changes to HASS.

**Comment by LinuxChristian** [comment]
The switch has now died with the same error,

`2017-12-28 10:32:12 WARNING (MainThread) [homeassistant.components.switch] Updating dlink switch took longer than the scheduled update interval 0:00:30`

Let me just check my changes to HASS again. Otherwise I don't quite know where the problem could be.

**Comment by dinkonin** [comment]
Same problem with firmware V2.23b02, any progress ?

**Comment by frog32** [comment]
No I still have the same issue but now I am moving away from d-link.

**Comment by LinuxChristian** [comment]
Sorry for the late reply. Summer holiday season :beach_umbrella:

No progress unfortunately. I cannot find the problem. It is only related to home assistant. I cannot recreate it using the library in standalone mode. So it must be something with the way HASS calls the library (I have added throttle control to test if the frequency of calls was a problem) or perhaps HASS stores some information the library does not (but I have also added automatic refresh of auth for long running processes).

So I don't know what else to test. But if anyone does any progress please let me know.
